global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'agent-intelligence'
    static_configs:
      - targets: ['agent-intelligence:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'orchestration-pipeline'
    static_configs:
      - targets: ['orchestration-pipeline:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'capability-registry'
    static_configs:
      - targets: ['capability-registry:3003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'security-gateway'
    static_configs:
      - targets: ['security-gateway:3004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333'] 